# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20160714_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='numero',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
