# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_estado', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('monto', models.IntegerField()),
                ('id_trabajador2', models.IntegerField()),
                ('id_trabajo', models.IntegerField()),
                ('id_estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rif', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(null=True)),
                ('status', models.BooleanField()),
                ('observacion', models.TextField()),
                ('cobrado', models.BooleanField()),
                ('id_trabajador1', models.IntegerField()),
                ('id_cliente1', models.IntegerField()),
            ],
        ),
    ]
