# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpDesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='clave',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rif',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
