# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpDesk', '0003_auto_20160708_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='fechaVisita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
