# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpDesk', '0005_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='id_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpDesk.Estados'),
        ),
    ]
