# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpDesk', '0006_trabajo_id_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(),
        ),
    ]
