# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpDesk', '0009_auto_20160709_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
    ]
