# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpDesk', '0013_auto_20160709_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='id_trabajador',
            field=models.ManyToManyField(blank=True, null=True, to='helpDesk.Trabajador'),
        ),
    ]
