# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpDesk', '0014_auto_20160709_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='id_trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpDesk.Trabajador'),
        ),
    ]
