# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpDesk', '0015_auto_20160709_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='id_trabajador',
            field=models.ManyToManyField(to='helpDesk.Trabajador'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='id_trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpDesk.Trabajador'),
        ),
    ]
