# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpDesk', '0017_auto_20160713_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='id_trabajador',
            field=models.ManyToManyField(to='helpDesk.Trabajador'),
        ),
    ]
