# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpDesk', '0018_auto_20160719_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='id_trabajador',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
