# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpDesk', '0019_auto_20160719_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='id_trabajador',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='id_trabajador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
