# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpDesk', '0021_auto_20160721_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='id_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpDesk.Estados'),
        ),
    ]
